name: tp0
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: python3 /main.py
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    networks:
    - testing_net
    volumes:
    - ./server/config.ini:/config.ini
  client1:
    container_name: client1
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=1
    - LOGGING_LEVEL=DEBUG
    - NOMBRE=Santiago Lionel
    - APELLIDO=Lorca
    - DOCUMENTO=30904465
    - NACIMIENTO=1999-03-17
    - NUMERO=7574
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client/config.yaml:/config.yaml

  client2:
    container_name: client2
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=2
    - LOGGING_LEVEL=DEBUG
    - NOMBRE=SAMUEL
    - APELLIDO=CARRANZA
    - DOCUMENTO=38764216
    - NACIMIENTO=1999-05-11
    - NUMERO=1355
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client/config.yaml:/config.yaml

  client3:
    container_name: client3
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=3
    - LOGGING_LEVEL=DEBUG
    - NOMBRE=Priscila Abigail
    - APELLIDO=Pedone
    - DOCUMENTO=31552640
    - NACIMIENTO=1980-04-30
    - NUMERO=6508
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client/config.yaml:/config.yaml

  client4:
    container_name: client4
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=4
    - LOGGING_LEVEL=DEBUG
    - NOMBRE=Thiago Nicolas
    - APELLIDO=Pereyra
    - DOCUMENTO=22556126
    - NACIMIENTO=1984-12-29
    - NUMERO=8797
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client/config.yaml:/config.yaml

  client5:
    container_name: client5
    image: client:latest
    entrypoint: /client
    environment:
    - CLI_ID=5
    - LOGGING_LEVEL=DEBUG
    - NOMBRE=Pablo Daniel
    - APELLIDO=Sanchez
    - DOCUMENTO=31537527
    - NACIMIENTO=1996-08-24
    - NUMERO=5154
    networks:
    - testing_net
    depends_on:
    - server
    volumes:
    - ./client/config.yaml:/config.yaml
    
networks:
  testing_net:
    ipam:
      driver: default
      config:
      - subnet: 172.25.125.0/24
